<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="OrgRepGroup.aspx.cs" Inherits="CyberCity.OrgRepGroup" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <link href="css/CreatingEntity.css" rel="stylesheet" />
    <link href="css/GridView.css" rel="stylesheet" />
    <link href="Content/bootstrap.css" rel="stylesheet" />

    <asp:Panel ID="Panel1" runat="server" BorderColor="#cccccc" BorderStyle="Solid" Width="100%">
        <div style="text-align:center;">
            <h1>Organizationl Reps!</h1>
            <p>Here, you can see the list of students that have registered with CyberDay under your respective code. If you wish to remove a student, you can do so here</p>
        </div>

        <asp:Table ID="Table1" runat="server" CellPadding="50" CellSpacing="50" HorizontalAlign="center">
            <asp:TableRow>
                <asp:TableCell>
                    <asp:GridView ID="grdOrgStudent" runat="server" 
                        AutoGenerateColumns="true" 
                        AutoGenerateDeleteButton="true"
                        AllowPaging="true" 
                        CssClass="Grid" 
                        AlternatingRowStyle-CssClass="alt" 
                        PagerStyle-CssClass="pgr">
                    </asp:GridView>
                </asp:TableCell>
            </asp:TableRow>

        </asp:Table>


    </asp:Panel>


</asp:Content>
